apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: conexao-solidaria
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  # Reach the UI for the demo via:
  # kubectl port-forward svc/prometheus 9090:9090 -n conexao-solidaria
