using System.Security.Cryptography;

namespace Campaigns.Api.Security;

public static class RsaPublicKeyProvider
{
    public static RSA Load(string publicKeyPath)
    {
        if (!File.Exists(publicKeyPath))
            throw new FileNotFoundException(
                "JWT public key not found. Copy jwt-public.pem generated by Identity.Api into " +
                "this path (in K8s, mount both from the same Secret instead).", publicKeyPath);

        var rsa = RSA.Create();
        rsa.ImportFromPem(File.ReadAllText(publicKeyPath));
        return rsa;
    }
}
